openapi: 3.0.0
info:
  title: Citas API
  description: API para reservas cita
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor Local
paths:
  /users:
    get:
      summary: Obtener todos los clientes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Crear un nuevo clientes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Cliente creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string

name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t sarapiraquive/adelantoscd:$(git rev-parse --short HEAD) .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push sarapiraquive/adelantoscd:$(git rev-parse --short HEAD)
