openapi: 3.0.0
info:
  title: Citas API
  description: API para reservas cita
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor Local
paths:
  /users:
    get:
      summary: Obtener todos los clientes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Crear un nuevo clientes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Cliente creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
