name: Continuous Delivery

on:
  push:
    branches: ['main']
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el proyecto
        uses: actions/checkout@v4
      - name: Instalando java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando gradle
        uses: gradle/gradle-build-action@v2
      - name: Compilando el proyecto build project
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push imagen Docker
        run: |
          docker build -t sarapiraquive/adelantoscd:latest .
          docker push sarapiraquive/adelantoscd:latest 





