name: Docker Build and Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Current Version
        id: get_version
        run: |
          # Reemplaza esta línea con el comando para obtener la versión actual de tu proyecto
          CURRENT_VERSION=$(grep 'version' build.gradle | sed 's/.*=//' | sed "s/'//g")
          echo "::set-output name=version::$CURRENT_VERSION"

      - name: Increment Version
        id: increment_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.version }}
          MAJOR=$(echo "$CURRENT_VERSION" | cut -d'.' -f1)
          MINOR=$(echo "$CURRENT_VERSION" | cut -d'.' -f2)
          PATCH=$(echo "$CURRENT_VERSION" | cut -d'.' -f3)
          NEW_PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "::set-output name=version::$NEW_VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sarapiraquive/adelantoscd:${{ steps.increment_version.outputs.version }}