name: Continuos Integration
on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el proyecto
        uses: actions/checkout@v4
      - name: Instalando Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compilando el proyecto build project
        run: ./gradlew build